# Generated by Django 5.2.5 on 2025-09-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20250525_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('logo', models.ImageField(help_text='Рекомендуемый размер: 200x100px', upload_to='partners/logos/', verbose_name='Логотип')),
                ('website_url', models.URLField(help_text='Полный URL сайта партнера (например: https://example.com)', verbose_name='Ссылка на сайт')),
                ('description', models.TextField(blank=True, help_text='Краткое описание деятельности партнера', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Отметьте, если партнер активен и должен отображаться на сайте', verbose_name='Активный партнер')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['is_active'], name='core_partne_is_acti_bf02d0_idx'), models.Index(fields=['order'], name='core_partne_order_ee7671_idx')],
            },
        ),
    ]
